In [5]:

votes = ["ABC","ACB","ABC","ACB","ACB"]
dims = len(votes[0])
rank_mat = [[0]*dims] * dims

In [6]:
rank_mat

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [7]:
if 'A' > 'B':
    print("A is greater")
else:
    print("B is greater")

B is greater


In [8]:
"" + "a"

'a'

In [10]:
if 'X' > 'W':
    print("X is smaller")
else:
    print("W is smaller")

X is smaller


In [11]:
ord('W')

87

In [12]:
ord('X')

88

In [28]:

class Solution:
    def rankTeams(self, votes):
        if len(votes) == 1:
            return votes[0]
        if len(votes[0]) == 1:
            return votes[0]
        
        dicti = collections.defaultdict()
        for i in votes[0]:
            dicti[i] = [0]*len(votes[0])
            
        for vote in votes:
            for j in range(len(vote)):
                dicti[vote[j]][j] += 1
                
        print(dicti.items())
        ans = ""
        for char,code in(sorted(dicti.items(),key=lambda x:(x[1],-ord(x[0])),reverse=True)):
            ans+=char
        return ans

In [29]:
s = Solution()

In [30]:
import collections

In [31]:
s.rankTeams(["ABC","ACB","ABC","ACB","ACB"])

dict_items([('A', [5, 0, 0]), ('B', [0, 2, 3]), ('C', [0, 3, 2])])


'ACB'

In [40]:
a = [[5, 2, 4], [5, 2, 3]]

In [41]:
sorted(a, key = lambda x: x)

[[5, 2, 3], [5, 2, 4]]

In [140]:
class Solution:
    
    def getAns(self, bloomDay,elem, m , k):
        print("day=",elem)
        bloomed = bloomDay.copy()
        for i, bd in enumerate(bloomed):
            if bd<=elem:
                bloomed[i] = 1
            else:
                bloomed[i] = 0
        print("bloomDay = ",bloomDay)
        print("bloomed = ",bloomed)
        # finding connected components length
        cc_len = 0
        cc = []
        for j, e in enumerate(bloomed):
            if e == 1:
                cc_len+=1
            if e==0 or j == len(bloomed) - 1:
                cc.append(cc_len)
                cc_len = 0
        print("cc = ", cc)
        bouquets_possible = 0

        for bloomed_nearby in cc:
            bouquets_possible+=bloomed_nearby//k

        print("bouquets_possible = ", bouquets_possible)
        return bouquets_possible
    
    def minDays(self, bloomDay, m: int, k: int) -> int:
        distinct_elem = sorted(set(bloomDay))
        print("distinct_elem = ",distinct_elem)
        low = 0
        high = len(distinct_elem)  -1
        while(low<=high):
            print("low = ", low)
            print("high = ", high)
            middle = (low+high)//2
            print("middle = ", middle)
            ans = self.getAns(bloomDay, distinct_elem[middle], m , k)
            if ans<m:
                low = middle+1
                print("low updated = ", low)
            elif ans>m:
                if(low == high):
                    return distinct_elem[middle]
                high = middle-1
                print("high updated to  = ", high)
            else:
                if middle==0 or self.getAns(bloomDay, distinct_elem[middle-1], m , k)<m:
                    print("answer =  ",distinct_elem[middle] )
                    return distinct_elem[middle]
                high = middle-1
        return -1
    
    
    

In [141]:
s = Solution()

In [142]:
l = [3542,4862,3568,3602,2074,2056,1330,923,2362,4948,1403,1208,5554,2591,2567,4857,266,4274,4995,863,4167,3389,2515,2778,955,5152,4232,4154,2041,5169,574,4786,3096,252,2501,1397,1910,2722,3116,2707,2837,409,488,2048,2546,4196,580,4434,2361,5190,4842,4914,487,3047,1676,3716,737,5378,244,3565,7,3672,4115,3985,123,4708,1701,5649,3961,1138,1254,3692,366,4342,4225,1240,2286,986,4111,1247,2992,5391,4497,1472,241,4530,4416,1842,1590,4607,588,3379,1895,5364,4133,418,1387,5113,3352,4965,4909,2216,1295,4531,4171,3224,5407,1654,3142,4662,444,1538,1431,844,2759,2735,3760,2605,1546,3630,4066,1870,410,3858,480,2389,1905,3553,638,1606,1786,1804,3355,2898,1126,108,908,4194,4782,2619,272,20,5102,4344,3158,1867,2484,1462,4269,1382,2215,3233,3425,3435,401,4660,5201,317,5149,1249,2070,5309,846,2839,1738,3207,1155,4055,702,3625,3561,4486,5652,2224,185,3269,2144,1757,3861,302,3431,5481,2042,2979,3915,3935,1976,1347,1360,3445,1733,3334,1252,5310,1557,4471,4836,993,2441,3554,2204,2884,3645,279,1346,2783,3013,1531,1066,4635,5630,4235,2655,4981,1781,353,3809,382,370,2352,2815,935,634,4329,5396,5420,3199,2868,1583,839,468,5320,5572,4319,4026,1632,3930,682,5059,2066,1078,1225,801,3306,278,52,4287,1857,1214,668,3770,1445,4143,5332,1037,277,4646,1118,4473,5238,3528,2294,246,514,2395,4101,2244,731,2975,973]
m = 11
k = 11

s.minDays(l,m,k)

distinct_elem =  [7, 20, 52, 108, 123, 185, 241, 244, 246, 252, 266, 272, 277, 278, 279, 302, 317, 353, 366, 370, 382, 401, 409, 410, 418, 444, 468, 480, 487, 488, 514, 574, 580, 588, 634, 638, 668, 682, 702, 731, 737, 801, 839, 844, 846, 863, 908, 923, 935, 955, 973, 986, 993, 1037, 1066, 1078, 1118, 1126, 1138, 1155, 1208, 1214, 1225, 1240, 1247, 1249, 1252, 1254, 1295, 1330, 1346, 1347, 1360, 1382, 1387, 1397, 1403, 1431, 1445, 1462, 1472, 1531, 1538, 1546, 1557, 1583, 1590, 1606, 1632, 1654, 1676, 1701, 1733, 1738, 1757, 1781, 1786, 1804, 1842, 1857, 1867, 1870, 1895, 1905, 1910, 1976, 2041, 2042, 2048, 2056, 2066, 2070, 2074, 2144, 2204, 2215, 2216, 2224, 2244, 2286, 2294, 2352, 2361, 2362, 2389, 2395, 2441, 2484, 2501, 2515, 2546, 2567, 2591, 2605, 2619, 2655, 2707, 2722, 2735, 2759, 2778, 2783, 2815, 2837, 2839, 2868, 2884, 2898, 2975, 2979, 2992, 3013, 3047, 3096, 3116, 3142, 3158, 3199, 3207, 3224, 3233, 3269, 3306, 3334, 3352, 3355, 3379, 3389, 3425, 3431, 3435, 3445, 3528, 3

4948

In [96]:
ss=[1,10,3,10,2]
sorted(set(ss))

[1, 2, 3, 10]

## Maximum Swap

In [143]:
class Solution:
    def maximumSwap(self, num: int) -> int:
        
        n = sorted([(i,int(n)) for i, n in enumerate(str(num))], key = lambda x: x[1],reverse=True)
        print(n)
        ans = ""
        flag = 0
        for i, x in enumerate(str(num)):
            print("i = ",i)
            print("n[i] = ",n[i])
            x = int(x)
            if n[i][1]!=x:
                j = i
                while j+1<=len(str(num))-1 and n[j][1]==n[j+1][1]:
                    j+=1
                flag = 1
                elem_to_replace = x
                indice = i
                replacement_indice = n[j][0]
                elem_replacement = n[j][1]
                break
        if flag == 0:
            return num
        
        
        
        print("elem_to_replace = ",elem_to_replace)
        print("indice = ",indice)
        print("elem_replacement = ",elem_replacement)
        print("replacement_indice = ",replacement_indice)
        
        
        temp = elem_replacement
        
        xx = [e for e in str(num)]
        xx[replacement_indice] = str(elem_to_replace)
        xx[indice] = str(elem_replacement)
        
        ans = int("".join(xx))
        return ans
s = Solution()
s. maximumSwap(1993)

[(1, 9), (2, 9), (3, 3), (0, 1)]
i =  0
n[i] =  (1, 9)
elem_to_replace =  1
indice =  0
elem_replacement =  9
replacement_indice =  2


9913

## 1524. Number of Sub-arrays With Odd Sum

In [164]:
class Solution:
    def createSubarray(self, arr, curr_arr, ans, i):
        if i==len(arr):
            ans.append(curr_arr)
            return
        
        self.createSubarray(arr, curr_arr + [arr[i]], ans, i+1)
        self.createSubarray(arr, curr_arr, ans, i+1)
        
        return ans
    
    def numOfSubarrays(self, arr):
        odd_sum = 0
        subArrays = self.createSubarray(arr, [], [], 0)
        subArrays = [list(item) for item in set(tuple(row) for row in subArrays)]
        print(subArrays)
        for subArray in subArrays:
                if sum(subArray)%2 != 0:
                    odd_sum+=1
        return odd_sum
        
s = Solution()
s.numOfSubarrays([1,2,3,4,5,6,7])


[[1, 2, 3, 4, 5, 6, 7], [1, 5, 7], [1, 4, 6, 7], [1, 2, 3, 7], [1, 2, 4, 6], [4, 6, 7], [3, 4, 5, 6], [2, 4, 5], [1, 2, 5, 7], [3, 6], [2, 3, 4, 5, 6], [2, 6, 7], [2, 4], [1, 2, 5, 6, 7], [1, 2, 4, 5, 6, 7], [2, 4, 7], [3, 4, 6, 7], [1, 2, 3, 5, 6], [1, 3, 5, 6], [6], [1, 4, 5, 6, 7], [1, 3, 4], [1, 2, 3, 4, 5, 6], [3, 4, 5], [1, 3, 4, 7], [1, 3, 4, 5, 6, 7], [1, 2, 4, 6, 7], [], [1, 2, 3, 4, 6, 7], [3, 5, 6], [2, 3, 4, 5, 6, 7], [1, 3, 6, 7], [5, 7], [1, 2, 3, 4], [2, 3, 4, 6], [4, 5, 6], [1, 3, 6], [1, 4, 5], [1, 3], [3, 4, 7], [3, 5, 6, 7], [2, 3, 5, 6, 7], [2, 3, 5, 7], [2, 3, 6], [1, 5, 6], [1], [5, 6, 7], [1, 2, 3, 6], [1, 2, 4, 5], [2, 5, 6], [2, 4, 5, 6, 7], [1, 4, 7], [1, 5], [2, 4, 5, 6], [1, 2, 3, 5, 6, 7], [2, 3, 4, 6, 7], [3], [1, 6, 7], [2, 4, 6, 7], [3, 5], [1, 2, 4, 7], [1, 2, 3], [1, 7], [2, 6], [1, 2, 6, 7], [3, 4, 5, 6, 7], [5], [3, 7], [4, 6], [1, 3, 4, 5, 6], [1, 2, 3, 4, 6], [1, 2, 5], [1, 3, 4, 6], [3, 6, 7], [1, 3, 4, 6, 7], [1, 2, 3, 5, 7], [2, 5, 6, 7], [1, 3,

64

## 1074. Number of Submatrices That Sum to Target

In [165]:
class Solution:
    def numSubmatrixSumTarget(self, matrix: List[List[int]], target: int) -> int:
        
        

SyntaxError: unexpected EOF while parsing (<ipython-input-165-97a9775df7a6>, line 4)

In [166]:
matrix = [[0,1,0],[1,1,1],[0,1,0]]

In [180]:
sm

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [197]:
# sm = [[0] * len(matrix[0])]*len(matrix)
sm = [[None]*len(matrix[0]) for _ in range(len(matrix))]
for i in range(len(matrix)):
#     print("*"*20)
    for j in range(len(matrix[0])):
        ur = 0
        bl = 0
        ul = 0
        if i-1>=0:
            ur = sm[i-1][j]
        if j-1>=0:
            bl = sm[i][j-1]
        if i-1>=0 and j-1>=0:
            ul = sm[i-1][j-1]
#         print("ur, bl , ul = ",ur, bl , ul)
#         print("inserted value  = ",ur + bl - ul +matrix[i][j])
        sm[i][j] = ur + bl - ul +matrix[i][j]
#         print(np.matrix(sm))


        

In [198]:
sm


[[0, 1, 1], [1, 3, 4], [1, 4, 5]]

In [199]:
import numpy as np
print(np.matrix(sm))

[[0 1 1]
 [1 3 4]
 [1 4 5]]


In [200]:
print(np.matrix(matrix))

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [186]:
sm

[[1, 3, 2], [1, 3, 2], [1, 3, 2]]

In [190]:
sm[0][1] = 100

In [212]:
sm

[[0, 1, 1], [1, 3, 4], [1, 4, 5]]

In [220]:
xx = []
for i in range(len(matrix)):
    for j in range(i, len(matrix)):
        xx.append([i, j])

In [221]:
xx

[[0, 0], [0, 1], [0, 2], [1, 1], [1, 2], [2, 2]]

In [222]:
yy = []
for i in range(len(matrix[0])):
    for j in range(i, len(matrix[0])):
        yy.append([i, j])

In [223]:
yy

[[0, 0], [0, 1], [0, 2], [1, 1], [1, 2], [2, 2]]

In [231]:
diff_sums = []
for x in xx:
    for y in yy:
        xmin, ymin, xmax, ymax = y[0], x[0], y[1], x[1]
        print(x, y)
#         diff_sums.append(sm)
        ur = 0
        bl = 0
        ul = 0
        if xmin-1>=0:
            ur = sm[xmin-1][ymax]
        
        if ymin-1>=0:
            bl = sm[xmin][ymin-1]
        
        if xmin-1>=0 and ymin-1>=0:
            ul = sm[xmin-1][ymin-1]
        
        subSum = sm[xmax][ymax] - ur - bl + ul
        print(subSum)
        if subSum==0:
            print("xmin, ymin, xmax, ymax = ",xmin, ymin, xmax, ymax)
            

[0, 0] [0, 0]
0
xmin, ymin, xmax, ymax =  0 0 0 0
[0, 0] [0, 1]
1
[0, 0] [0, 2]
1
[0, 0] [1, 1]
1
[0, 0] [1, 2]
1
[0, 0] [2, 2]
0
xmin, ymin, xmax, ymax =  2 0 2 0
[0, 1] [0, 0]
1
[0, 1] [0, 1]
3
[0, 1] [0, 2]
4
[0, 1] [1, 1]
2
[0, 1] [1, 2]
3
[0, 1] [2, 2]
1
[0, 2] [0, 0]
1
[0, 2] [0, 1]
4
[0, 2] [0, 2]
5
[0, 2] [1, 1]
3
[0, 2] [1, 2]
4
[0, 2] [2, 2]
1
[1, 1] [0, 0]
1
[1, 1] [0, 1]
3
[1, 1] [0, 2]
4
[1, 1] [1, 1]
1
[1, 1] [1, 2]
2
[1, 1] [2, 2]
1
[1, 2] [0, 0]
1
[1, 2] [0, 1]
4
[1, 2] [0, 2]
5
[1, 2] [1, 1]
2
[1, 2] [1, 2]
3
[1, 2] [2, 2]
1
[2, 2] [0, 0]
0
xmin, ymin, xmax, ymax =  0 2 0 2
[2, 2] [0, 1]
3
[2, 2] [0, 2]
4
[2, 2] [1, 1]
1
[2, 2] [1, 2]
2
[2, 2] [2, 2]
0
xmin, ymin, xmax, ymax =  2 2 2 2


In [218]:
np.matrix(sm)

matrix([[0, 1, 1],
        [1, 3, 4],
        [1, 4, 5]])

In [219]:
np.matrix(matrix)

matrix([[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]])

In [253]:
class Solution:
    def numSubmatrixSumTarget(self, matrix, target):
        print(np.matrix(matrix))
        # sm = [[0] * len(matrix[0])]*len(matrix)
        sm = [[None]*len(matrix[0]) for _ in range(len(matrix))]
        for i in range(len(matrix)):
        #     print("*"*20)
            for j in range(len(matrix[0])):
                ur = 0
                bl = 0
                ul = 0
                if i-1>=0:
                    ur = sm[i-1][j]
                if j-1>=0:
                    bl = sm[i][j-1]
                if i-1>=0 and j-1>=0:
                    ul = sm[i-1][j-1]
        #         print("ur, bl , ul = ",ur, bl , ul)
        #         print("inserted value  = ",ur + bl - ul +matrix[i][j])
                sm[i][j] = ur + bl - ul +matrix[i][j]
        #         print(np.matrix(sm))
        
        print(np.matrix(sm))
        xx = []
        for i in range(len(matrix)):
            for j in range(i, len(matrix)):
                xx.append([i, j])
#         print(xx)
        yy = []
        for i in range(len(matrix[0])):
            for j in range(i, len(matrix[0])):
                yy.append([i, j])
        
#         print(yy)
        diff_sums = []
        count=0
        print("*"*30)
        for x in xx:
            for y in yy:  
                ymin, xmin, ymax, xmax = y[0], x[0], y[1], x[1]
#                 print(x, y)
                ur = 0
                bl = 0
                ul = 0
                if xmin-1>=0:
                    ur = sm[xmin-1][ymax]
                if ymin-1>=0:
                    bl = sm[xmin][ymin-1]
                if xmin-1>=0 and ymin-1>=0:
                    ul = sm[xmin-1][ymin-1]
                subSum = sm[xmax][ymax] - ur - bl + ul
                if xmin == 0 and ymin==1 and xmax==1 and ymax==1:
                    print("subSum = ", subSum)
                    print(sm[xmax][ymax], ur, bl,ul)
                print("subSum = ",subSum)
                print("xmin, ymin, xmax, ymax = ",xmin, ymin, xmax, ymax)
                if subSum==target:
#                     print("xmin, ymin, xmax, ymax = ",xmin, ymin, xmax, ymax)
#                     print("target = ", subSum)
                    count+=1
        return count






In [254]:
s = Solution()
s.numSubmatrixSumTarget([[1,-1],[-1,1]], 0)

[[ 1 -1]
 [-1  1]]
[[1 0]
 [0 0]]
******************************
subSum =  1
xmin, ymin, xmax, ymax =  0 0 0 0
subSum =  0
xmin, ymin, xmax, ymax =  0 0 0 1
subSum =  -1
xmin, ymin, xmax, ymax =  0 1 0 1
subSum =  0
xmin, ymin, xmax, ymax =  0 0 1 0
subSum =  0
xmin, ymin, xmax, ymax =  0 0 1 1
subSum =  -1
0 0 1 0
subSum =  -1
xmin, ymin, xmax, ymax =  0 1 1 1
subSum =  -1
xmin, ymin, xmax, ymax =  1 0 1 0
subSum =  0
xmin, ymin, xmax, ymax =  1 0 1 1
subSum =  1
xmin, ymin, xmax, ymax =  1 1 1 1


4

## NUMBER LOWER THAN THE CURRENT NUMBER

In [67]:
class Solution:
    def positionOfNumInArr(self, arr, num):
        low = 0
        high = len(arr)-1
        while(low<=high):
            middle = (low + high)//2
            
            if (arr[middle] == num and middle-1>=0 and arr[middle-1]!=num) or (middle==0 and arr[middle]==num):
                return middle
            
            elif arr[middle]>=num:
                high = middle-1
            else:
                low = middle+1
        return -1
    
    def smallerNumbersThanCurrent(self, nums):
        
        sorted_nums = sorted(nums)
        
        ans = []
        
        for num in nums:
            pos = self.positionOfNumInArr(sorted_nums, num)
            ans.append(max(0, pos))
        
        return ans

In [68]:
s = Solution()
arr = [1,3,5,7]



In [69]:
s.smallerNumbersThanCurrent(arr)

[0, 1, 2, 3]

In [71]:
[1]*8+[2]*9

[1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]

## RAIN WATER TRAPPING

In [18]:
class Solution:

    def trap(self, height):
        rMax = []
        lMax = []
        for i in range(len(height)):
            _max = height[i]
            for j in range(i+1, len(height)):
                _max = max(_max, height[j])
                    
            rMax.append(_max)
            
        for i in range(len(height)-1, -1, -1):
            _max = height[i]
            for j in range(i-1, -1,-1):
                _max = max(_max, height[j])
            lMax.append(_max)
        lMax.reverse()
            
        print(rMax)
        print(lMax)
       
    
        

In [19]:
s = Solution()


In [20]:

height = [1,2,5,4,1]
s.trap(height)


[5, 5, 4, 1, -1]
[-1, 1, 2, 5, 5]


In [143]:
a = [1,2,3]

In [144]:
a.reverse()

In [145]:
a

[3, 2, 1]

In [10]:
height = [1, 2, 3, 4, 1]
leftGreater = []


for i in range(len(height)-1, -1, -1):
    min_ind = -1
    for j in range(i-1, -1,-1):
        if height[j]>=height[i]:
            min_ind = j
            break
    leftGreater.append(min_ind)

leftGreater.reverse()
print(leftGreater)

[-1, -1, -1, -1, 3]


In [170]:
leftGreater

[1, 2, 3, -1]

In [ ]:
7, 8, 9, 10